.\"                              hey, Emacs:   -*- nroff -*-
.\" sequtils is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH CLUSTALWTOFASTA 1 "April 3, 2002"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
clustalwtofasta \- a program to convert a clustalw alignment file
into a FASTA format file containing the aligned sequences
.SH SYNOPSIS
.B clustalwtofasta -i <infile> -o <outfile>
.RI [ options ]
.SH DESCRIPTION
\fBclustalwtofasta\fP reads in a CLUSTALW alignment from a file and
outputs the aligned sequences in FASTA format, in the same order that
they appear in the CLUSTALW file
.SH OPTIONS
\fBclustalwtofasta\fP accepts the following options:
.TP
.B \-i <infile>
specify the file containing the CLUSTALW alignment
.TP
.B \-o <outfile>
specify a file name to which to write the FASTA sequences.  If no 
outfile is provided, the sequences are written to stdout
.\" .SH "SEE ALSO"
.\" .BR foo (1), 
.\" .BR bar (1).
.SH AUTHOR
Kevin Thornton <kevin@krthornt.uchicago.edu>.
