.\"                              hey, Emacs:   -*- nroff -*-
.\" sequtils is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH SEQUTILS 1 "April 3, 2002"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sequtils \- a collection of programs that do things with DNA sequence data
.SH SYNOPSIS
The \fBsequtils\fP package contains the following binaries, which have their
own man pages: \fBclustalwtofasta\fP, \fBtrimallgaps\fP, \fBrevcom\fP, 
\fBtoLDhat\fP, and \fBtohudson2001\fP.

These programs depend on the libsequence library, also available from the author.
.SH DESCRIPTION
\fBsequtils\fP washes your windows, mends your fences, mows your lawn...
.PP
.\" .SH "SEE ALSO"
.\" .BR foo (1), 
.\" .BR bar (1).
.SH AUTHOR
Kevin Thornton <k-thornton@uchicago.edu>
